package fe.when.ad.f;

import androidx.appcompat.widget.Toolbar;
import androidx.exifinterface.media.ExifInterface;
import com.alipay.sdk.m.p.e;
import com.baidu.android.util.devices.MemoryUtils;
import com.google.common.net.HttpHeaders;
import com.google.protobuf.MessageLiteToString;
import com.itextpdf.text.pdf.PRTokeniser;
import fe.when.ad.c.qw;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;

public class s0 extends y0 implements Comparable<s0> {
    public static final s0 A = new s0("CalGray");
    public static final s0 A0 = new s0("DisplayDocTitle");
    public static final s0 A1 = new s0("Formula");
    public static final s0 A2 = new s0("LastPage");
    public static final s0 A3 = new s0("Outlines");
    public static final s0 A4 = new s0("RT");
    public static final s0 A5 = new s0("TOCI");
    public static final s0 A6 = new s0("ZapfDingbats");
    public static final s0 B = new s0("CalRGB");
    public static final s0 B0 = new s0("Div");
    public static final s0 B1 = new s0("FullScreen");
    public static final s0 B2 = new s0("Launch");
    public static final s0 B3 = new s0("OutputCondition");
    public static final s0 B4 = new s0("Ruby");
    public static final s0 B5 = new s0("ToUnicode");
    public static final s0 B6 = new s0("Zoom");
    public static final s0 C = new s0("CapHeight");
    public static final s0 C0 = new s0("Document");
    public static final s0 C1 = new s0(ExifInterface.TAG_GAMMA);
    public static final s0 C2 = new s0("Layout");
    public static final s0 C3 = new s0("OutputConditionIdentifier");
    public static final s0 C4 = new s0("RunLengthDecode");
    public static final s0 C5 = new s0("Transparency");
    public static Map<String, s0> C6;
    public static final s0 D = new s0("Caption");
    public static final s0 D0 = new s0("DP");
    public static final s0 D1 = new s0("GoTo");
    public static final s0 D2 = new s0("Lbl");
    public static final s0 D3 = new s0("OutputIntent");
    public static final s0 D4 = new s0(ExifInterface.LATITUDE_SOUTH);
    public static final s0 D5 = new s0("Trapped");
    public static final s0 E = new s0("Catalog");
    public static final s0 E0 = new s0("DR");
    public static final s0 E1 = new s0("GoToR");
    public static final s0 E2 = new s0("LBody");
    public static final s0 E3 = new s0("OutputIntents");
    public static final s0 E4 = new s0(ExifInterface.TAG_SATURATION);
    public static final s0 E5 = new s0("TrimBox");
    public static final s0 F = new s0("Category");
    public static final s0 F0 = new s0("DS");
    public static final s0 F1 = new s0("Group");
    public static final s0 F2 = new s0("Length");
    public static final s0 F3 = new s0("P");
    public static final s0 F4 = new s0("Scope");
    public static final s0 F5 = new s0("TrueType");
    public static final s0 G = new s0("CCITTFaxDecode");
    public static final s0 G0 = new s0("Duplex");
    public static final s0 G1 = new s0("GTS_PDFX");
    public static final s0 G2 = new s0("LI");
    public static final s0 G3 = new s0("Page");
    public static final s0 G4 = new s0("Screen");
    public static final s0 G5 = new s0("TwoColumnLeft");
    public static final s0 H = new s0("Center");
    public static final s0 H0 = new s0("DuplexFlipShortEdge");
    public static final s0 H1 = new s0("GTS_PDFXVersion");
    public static final s0 H2 = new s0("Limits");
    public static final s0 H3 = new s0("PageLabels");
    public static final s0 H4 = new s0("Sect");
    public static final s0 H5 = new s0("TwoColumnRight");
    public static final s0 I = new s0("CenterWindow");
    public static final s0 I0 = new s0("DuplexFlipLongEdge");
    public static final s0 I1 = new s0("H");
    public static final s0 I2 = new s0("LineHeight");
    public static final s0 I3 = new s0("PageLayout");
    public static final s0 I4 = new s0("Shading");
    public static final s0 I5 = new s0("TwoPageLeft");
    public static final s0 J = new s0("CIDFontType0");
    public static final s0 J0 = new s0("DW");
    public static final s0 J1 = new s0("H1");
    public static final s0 J2 = new s0(HttpHeaders.LINK);
    public static final s0 J3 = new s0("PageMode");
    public static final s0 J4 = new s0("SigFlags");
    public static final s0 J5 = new s0("TwoPageRight");
    public static final s0 K = new s0("CIDFontType2");
    public static final s0 K0 = new s0(ExifInterface.LONGITUDE_EAST);
    public static final s0 K1 = new s0("H2");
    public static final s0 K2 = new s0(MessageLiteToString.LIST_SUFFIX);
    public static final s0 K3 = new s0("Pages");
    public static final s0 K4 = new s0("Simplex");
    public static final s0 K5 = new s0("Type");
    public static final s0 L = new s0("CIDSet");
    public static final s0 L0 = new s0("EF");
    public static final s0 L1 = new s0("H3");
    public static final s0 L2 = new s0("ListMode");
    public static final s0 L3 = new s0("PaintType");
    public static final s0 L4 = new s0("SinglePage");
    public static final s0 L5 = new s0("Type0");
    public static final s0 M = new s0("CIDSystemInfo");
    public static final s0 M0 = new s0("EmbeddedFile");
    public static final s0 M1 = new s0("H4");
    public static final s0 M2 = new s0("ListNumbering");
    public static final s0 M3 = new s0("Panose");
    public static final s0 M4 = new s0("Size");
    public static final s0 M5 = new s0("Type1");
    public static final s0 N = new s0("CIDToGIDMap");
    public static final s0 N0 = new s0("EmbeddedFiles");
    public static final s0 N1 = new s0("H5");
    public static final s0 N2 = new s0("Locked");
    public static final s0 N3 = new s0("Params");
    public static final s0 N4 = new s0("SMask");
    public static final s0 N5 = new s0("U");
    public static final s0 O = new s0("ClassMap");
    public static final s0 O0 = new s0("EncodedByteAlign");
    public static final s0 O1 = new s0("H6");
    public static final s0 O2 = new s0("LowerAlpha");
    public static final s0 O3 = new s0("Parent");
    public static final s0 O4 = new s0("SpaceAfter");
    public static final s0 O5 = new s0("UF");
    public static final s0 P = new s0("CO");
    public static final s0 P0 = new s0("Encoding");
    public static final s0 P1 = new s0("Headers");
    public static final s0 P2 = new s0("LowerRoman");
    public static final s0 P3 = new s0("ParentTree");
    public static final s0 P4 = new s0("SpaceBefore");
    public static final s0 P5 = new s0("Underline");
    public static final s0 Q = new s0("Code");
    public static final s0 Q0 = new s0("Encrypt");
    public static final s0 Q1 = new s0("Height");
    public static final s0 Q2 = new s0("LZWDecode");
    public static final s0 Q3 = new s0("Part");
    public static final s0 Q4 = new s0("Span");
    public static final s0 Q5 = new s0("UpperAlpha");
    public static final s0 R = new s0("Color");
    public static final s0 R0 = new s0("End");
    public static final s0 R1 = new s0("Helvetica");
    public static final s0 R2 = new s0("Matrix");
    public static final s0 R3 = new s0("Pattern");
    public static final s0 R4 = new s0("Start");
    public static final s0 R5 = new s0("UpperRoman");
    public static final s0 S = new s0("Colors");
    public static final s0 S0 = new s0("EndIndent");
    public static final s0 S1 = new s0("Helvetica-Bold");
    public static final s0 S2 = new s0("MacRomanEncoding");
    public static final s0 S3 = new s0("PatternType");
    public static final s0 S4 = new s0("StartIndent");
    public static final s0 S5 = new s0("URI");
    public static final s0 T = new s0(ExifInterface.TAG_COLOR_SPACE);
    public static final s0 T0 = new s0("EndOfBlock");
    public static final s0 T1 = new s0("Helvetica-Oblique");
    public static final s0 T2 = new s0("Marked");
    public static final s0 T3 = new s0("Perceptual");
    public static final s0 T4 = new s0("StdCF");
    public static final s0 T5 = new s0("Usage");
    public static final s0 U = new s0("ColorTransform");
    public static final s0 U0 = new s0("EndOfLine");
    public static final s0 U1 = new s0("Helvetica-BoldOblique");
    public static final s0 U2 = new s0("MarkInfo");
    public static final s0 U3 = new s0("Pg");
    public static final s0 U4 = new s0("StemV");
    public static final s0 U5 = new s0("UseAttachments");
    public static final s0 V = new s0("Collection");
    public static final s0 V0 = new s0("Exclude");
    public static final s0 V1 = new s0("HideMenubar");
    public static final s0 V2 = new s0("Mask");
    public static final s0 V3 = new s0("PickTrayByPDFSize");
    public static final s0 V4 = new s0("StructElem");
    public static final s0 V5 = new s0("UseNone");
    public static final s0 W = new s0("Colspan");
    public static final s0 W0 = new s0("Extensions");
    public static final s0 W1 = new s0("HideToolbar");
    public static final s0 W2 = new s0("MediaBox");
    public static final s0 W3 = new s0("Predictor");
    public static final s0 W4 = new s0("StructParent");
    public static final s0 W5 = new s0("UseOC");
    public static final s0 X = new s0("Column");
    public static final s0 X0 = new s0("ExtGState");
    public static final s0 X1 = new s0("HideWindowUI");
    public static final s0 X2 = new s0("MCID");
    public static final s0 X3 = new s0("Prev");
    public static final s0 X4 = new s0("StructParents");
    public static final s0 X5 = new s0("UseOutlines");
    public static final s0 Y = new s0("Columns");
    public static final s0 Y0 = new s0("Export");
    public static final s0 Y1 = new s0("I");
    public static final s0 Y2 = new s0("MCR");
    public static final s0 Y3 = new s0("PrevPage");
    public static final s0 Y4 = new s0("StructTreeRoot");
    public static final s0 Y5 = new s0("UserProperties");
    public static final s0 Z = new s0("Contents");
    public static final s0 Z0 = new s0("Event");
    public static final s0 Z1 = new s0("ICCBased");
    public static final s0 Z2 = new s0("Metadata");
    public static final s0 Z3 = new s0("Print");
    public static final s0 Z4 = new s0("Style");
    public static final s0 Z5 = new s0("UseThumbs");
    public static final s0 a0 = new s0("Count");
    public static final s0 a1 = new s0("F");
    public static final s0 a2 = new s0("ID");
    public static final s0 a3 = new s0("ModDate");
    public static final s0 a4 = new s0("PrintArea");
    public static final s0 a5 = new s0("Subject");
    public static final s0 a6 = new s0(ExifInterface.GPS_MEASUREMENT_INTERRUPTED);
    public static final s0 aaa = new s0("AppDefault");
    public static final s0 b0 = new s0("Courier");
    public static final s0 b1 = new s0("Fields");
    public static final s0 b2 = new s0("Identity");
    public static final s0 b3 = new s0("N");
    public static final s0 b4 = new s0("PrintClip");
    public static final s0 b5 = new s0("Subtype");
    public static final s0 b6 = new s0(e.g);
    public static final s0 c0 = new s0("Courier-Bold");
    public static final s0 c1 = new s0("Figure");
    public static final s0 c2 = new s0("Image");
    public static final s0 c3 = new s0("Name");
    public static final s0 c4 = new s0("PrintPageRange");
    public static final s0 c5 = new s0("Supplement");
    public static final s0 c6 = new s0("View");
    public static final s0 d0 = new s0("Courier-Oblique");
    public static final s0 d1 = new s0("Filespec");
    public static final s0 d2 = new s0("ImageMask");
    public static final s0 d3 = new s0("Named");
    public static final s0 d4 = new s0("PrintScaling");
    public static final s0 d5 = new s0("Symbol");
    public static final s0 d6 = new s0("ViewArea");
    public static final s0 ddd = new s0("Annot");
    public static final s0 e = new s0("AS");
    public static final s0 e0 = new s0("Courier-BoldOblique");
    public static final s0 e1 = new s0("Filter");
    public static final s0 e2 = new s0("Include");
    public static final s0 e3 = new s0("Names");
    public static final s0 e4 = new s0("Private");
    public static final s0 e5 = new s0(ExifInterface.GPS_DIRECTION_TRUE);
    public static final s0 e6 = new s0("ViewClip");
    public static final s0 eee = new s0("ArtBox");
    public static final s0 f = new s0("ASCII85Decode");
    public static final s0 f0 = new s0("CreationDate");
    public static final s0 f1 = new s0("First");
    public static final s0 f2 = new s0("Index");
    public static final s0 f3 = new s0("NewWindow");
    public static final s0 f4 = new s0("Producer");
    public static final s0 f5 = new s0("Table");
    public static final s0 f6 = new s0("ViewerPreferences");
    public static final s0 g = new s0("ASCIIHexDecode");
    public static final s0 g0 = new s0("Creator");
    public static final s0 g1 = new s0("FirstChar");
    public static final s0 g2 = new s0("Indexed");
    public static final s0 g3 = new s0("Next");
    public static final s0 g4 = new s0("Properties");
    public static final s0 g5 = new s0("Tabs");
    public static final s0 g6 = new s0("VisiblePages");
    public static final s0 ggg = new s0("All");
    public static final s0 h = new s0("Author");
    public static final s0 h0 = new s0("CropBox");
    public static final s0 h1 = new s0("FirstPage");
    public static final s0 h2 = new s0("Info");
    public static final s0 h3 = new s0("NextPage");
    public static final s0 h4 = new s0("Quote");
    public static final s0 h5 = new s0("TBody");
    public static final s0 h6 = new s0(ExifInterface.LONGITUDE_WEST);

    /* renamed from: i  reason: collision with root package name */
    public static final s0 f9757i = new s0(ExifInterface.GPS_MEASUREMENT_IN_PROGRESS);
    public static final s0 i0 = new s0("Crypt");
    public static final s0 i1 = new s0("FitH");
    public static final s0 i2 = new s0("Intent");
    public static final s0 i3 = new s0("None");
    public static final s0 i4 = new s0("R");
    public static final s0 i5 = new s0("TD");
    public static final s0 i6 = new s0("W2");

    /* renamed from: if  reason: not valid java name */
    public static final s0 f455if = new s0("AbsoluteColorimetric");
    public static final s0 j = new s0("B");
    public static final s0 j0 = new s0("CS");
    public static final s0 j1 = new s0("FitV");
    public static final s0 j2 = new s0("Interpolate");
    public static final s0 j3 = new s0("NonFullScreenPageMode");
    public static final s0 j4 = new s0("R2L");
    public static final s0 j5 = new s0("TR");
    public static final s0 j6 = new s0("Warichu");
    public static final s0 k = new s0("BackgroundColor");
    public static final s0 k0 = new s0("D");
    public static final s0 k1 = new s0("FitBH");
    public static final s0 k2 = new s0("IsMap");
    public static final s0 k3 = new s0("NonStruct");
    public static final s0 k4 = new s0("RB");
    public static final s0 k5 = new s0("Text");
    public static final s0 k6 = new s0("WC");
    public static final s0 l = new s0("BaseFont");
    public static final s0 l0 = new s0("DA");
    public static final s0 l1 = new s0("FitBV");
    public static final s0 l2 = new s0("ItalicAngle");
    public static final s0 l3 = new s0("Note");
    public static final s0 l4 = new s0("RBGroups");
    public static final s0 l5 = new s0("TextAlign");
    public static final s0 l6 = new s0("Width");
    public static final s0 m = new s0("BBox");
    public static final s0 m0 = new s0("DCTDecode");
    public static final s0 m1 = new s0("FitWindow");
    public static final s0 m2 = new s0("JavaScript");
    public static final s0 m3 = new s0("NumCopies");
    public static final s0 m4 = new s0("Rect");
    public static final s0 m5 = new s0("TextDecorationColor");
    public static final s0 m6 = new s0("Widths");
    public static final s0 mmm = new s0("AntiAlias");
    public static final s0 n = new s0("BibEntry");
    public static final s0 n0 = new s0("Decimal");
    public static final s0 n1 = new s0("Fl");
    public static final s0 n2 = new s0("JBIG2Decode");
    public static final s0 n3 = new s0("Nums");
    public static final s0 n4 = new s0("Reference");
    public static final s0 n5 = new s0("TextDecorationThickness");
    public static final s0 n6 = new s0("Win");
    public static final s0 nn = new s0("Annots");

    /* renamed from: o  reason: collision with root package name */
    public static final s0 f9758o = new s0("A85");
    public static final s0 o0 = new s0("Decode");
    public static final s0 o1 = new s0("Flags");
    public static final s0 o2 = new s0("JBIG2Globals");
    public static final s0 o3 = new s0("O");
    public static final s0 o4 = new s0("Registry");
    public static final s0 o5 = new s0("TextDecorationType");
    public static final s0 o6 = new s0("WinAnsiEncoding");
    public static final s0 p = new s0("BitsPerComponent");
    public static final s0 p0 = new s0("DecodeParms");
    public static final s0 p1 = new s0("FlateDecode");
    public static final s0 p2 = new s0("JPXDecode");
    public static final s0 p3 = new s0("Obj");
    public static final s0 p4 = new s0("RegistryName");
    public static final s0 p5 = new s0("TextIndent");
    public static final s0 p6 = new s0(ExifInterface.TAG_WHITE_POINT);

    /* renamed from: pf  reason: collision with root package name */
    public static final s0 f9759pf = new s0("AA");
    public static final s0 ppp = new s0("AHx");
    public static final s0 q = new s0("Bl");
    public static final s0 q0 = new s0("DefaultRGB");
    public static final s0 q1 = new s0("Fo");
    public static final s0 q2 = new s0("JS");
    public static final s0 q3 = new s0("OBJR");
    public static final s0 q4 = new s0("RelativeColorimetric");
    public static final s0 q5 = new s0("TFoot");
    public static final s0 q6 = new s0("WP");
    public static final s0 qqq = new s0("Art");
    public static final s0 r = new s0("BlackIs1");
    public static final s0 r0 = new s0("DescendantFonts");
    public static final s0 r1 = new s0("Font");
    public static final s0 r2 = new s0("Justify");
    public static final s0 r3 = new s0("ObjStm");
    public static final s0 r4 = new s0("Rendition");
    public static final s0 r5 = new s0("TH");
    public static final s0 r6 = new s0("WS");
    public static final s0 rrr = new s0("Artifact");
    public static final s0 s = new s0("BlockQuote");
    public static final s0 s0 = new s0("Descent");
    public static final s0 s1 = new s0("FontBBox");
    public static final s0 s2 = new s0("K");
    public static final s0 s3 = new s0("OC");
    public static final s0 s4 = new s0("Resources");
    public static final s0 s5 = new s0("THead");
    public static final s0 s6 = new s0("WT");

    /* renamed from: switch  reason: not valid java name */
    public static final s0 f456switch = new s0("AcroForm");
    public static final s0 t = new s0("BleedBox");
    public static final s0 t0 = new s0("Dest");
    public static final s0 t1 = new s0("FontDescriptor");
    public static final s0 t2 = new s0("Keywords");
    public static final s0 t3 = new s0("OCGs");
    public static final s0 t4 = new s0("RoleMap");
    public static final s0 t5 = new s0("TilingType");
    public static final s0 t6 = new s0("X");
    public static final s0 tt = new s0("Ascent");
    public static final s0 u = new s0("BM");
    public static final s0 u0 = new s0("Dests");
    public static final s0 u1 = new s0("FontFile");
    public static final s0 u2 = new s0("Kids");
    public static final s0 u3 = new s0("OCProperties");
    public static final s0 u4 = new s0("Root");
    public static final s0 u5 = new s0("Times-Roman");
    public static final s0 u6 = new s0("XML");
    public static final s0 v = new s0("Border");
    public static final s0 v0 = new s0("DeviceGray");
    public static final s0 v1 = new s0("FontFile2");
    public static final s0 v2 = new s0("L");
    public static final s0 v3 = new s0("OFF");
    public static final s0 v4 = new s0("Rotate");
    public static final s0 v5 = new s0("Times-Bold");
    public static final s0 v6 = new s0("XObject");
    public static final s0 vvv = new s0("Alt");
    public static final s0 w = new s0("Both");
    public static final s0 w0 = new s0("DeviceRGB");
    public static final s0 w1 = new s0("FontFile3");
    public static final s0 w2 = new s0("L2R");
    public static final s0 w3 = new s0("OneColumn");
    public static final s0 w4 = new s0("Row");
    public static final s0 w5 = new s0("Times-Italic");
    public static final s0 w6 = new s0("XRef");
    public static final s0 when = new s0("ActualText");
    public static final s0 x = new s0("C");
    public static final s0 x0 = new s0("DeviceCMYK");
    public static final s0 x1 = new s0("FontName");
    public static final s0 x2 = new s0("Lang");
    public static final s0 x3 = new s0("OpenAction");
    public static final s0 x4 = new s0("Rows");
    public static final s0 x5 = new s0("Times-BoldItalic");
    public static final s0 x6 = new s0("XStep");
    public static final s0 xxx = new s0("Alternate");
    public static final s0 y = new s0("CA");
    public static final s0 y0 = new s0("Differences");
    public static final s0 y1 = new s0("Form");
    public static final s0 y2 = new s0("Last");
    public static final s0 y3 = new s0("Order");
    public static final s0 y4 = new s0("RowSpan");
    public static final s0 y5 = new s0("Title");
    public static final s0 y6 = new s0("XYZ");
    public static final s0 z = new s0("ca");
    public static final s0 z0 = new s0("Direction");
    public static final s0 z1 = new s0("FormType");
    public static final s0 z2 = new s0("LastChar");
    public static final s0 z3 = new s0("Ordering");
    public static final s0 z4 = new s0("RP");
    public static final s0 z5 = new s0("TOC");
    public static final s0 z6 = new s0("YStep");

    /* renamed from: uk  reason: collision with root package name */
    public int f9760uk;

    static {
        new s0("3D");
        new s0("AC");
        new s0("Action");
        new s0("Activation");
        new s0("ADBE");
        new s0("adbe.pkcs7.detached");
        new s0("adbe.pkcs7.s4");
        new s0("adbe.pkcs7.s5");
        new s0("adbe.pkcs7.sha1");
        new s0("adbe.x509.rsa_sha1");
        new s0("Adobe.PPKLite");
        new s0("Adobe.PPKMS");
        new s0("AESV2");
        new s0("AESV3");
        new s0("AFRelationship");
        new s0("AIS");
        new s0("AllPages");
        new s0("AlternatePresentations");
        new s0("Alternates");
        new s0("And");
        new s0("Animation");
        new s0("AP");
        new s0("App");
        new s0("Asset");
        new s0("Assets");
        new s0("Attached");
        new s0("AuthEvent");
        new s0("Background");
        new s0("BaseEncoding");
        new s0("BaseVersion");
        new s0("BC");
        new s0("BG");
        new s0("BigFive");
        new s0("Binding");
        new s0("BindingMaterialName");
        new s0(ExifInterface.TAG_BITS_PER_SAMPLE);
        new s0("BlackPoint");
        new s0("Blinds");
        new s0("Bounds");
        new s0("Box");
        new s0("BS");
        new s0("Btn");
        new s0("ByteRange");
        new s0("C0");
        new s0("C1");
        new s0("Caret");
        new s0("cb");
        new s0("Cert");
        new s0("Certs");
        new s0("CF");
        new s0("CFM");
        new s0("Ch");
        new s0("CharProcs");
        new s0("CheckSum");
        new s0("CI");
        new s0("Circle");
        new s0("Cloud");
        new s0("CMD");
        new s0("Colorants");
        new s0("CollectionField");
        new s0("CollectionItem");
        new s0("CollectionSchema");
        new s0("CollectionSort");
        new s0("CollectionSubitem");
        new s0("Condition");
        new s0("Configs");
        new s0("Configuration");
        new s0("Configurations");
        new s0("ContactInfo");
        new s0("Content");
        new s0("Coords");
        new s0("CreatorInfo");
        new s0("CRL");
        new s0("CRLs");
        new s0("CuePoint");
        new s0("CuePoints");
        new s0("CYX");
        new s0("Data");
        new s0("DC");
        new s0("DCS");
        new s0("Deactivation");
        new s0("Default");
        new s0("DefaultCryptFilter");
        new s0("DefaultCMYK");
        new s0("DefaultGray");
        new s0("Desc");
        new s0("DestOutputProfile");
        new s0("DeviceN");
        new s0("Di");
        new s0("Dissolve");
        new s0("DL");
        new s0("Dm");
        new s0("DocMDP");
        new s0("DocOpen");
        new s0("DocTimeStamp");
        new s0("Domain");
        new s0("DOS");
        new s0("DSS");
        new s0("Dur");
        new s0("DV");
        new s0("EarlyChange");
        new s0("EFF");
        new s0("EFOpen");
        new s0("Embedded");
        new s0("Encode");
        new s0("EncryptMetadata");
        new s0("EPSG");
        new s0("ESIC");
        new s0("ETSI.CAdES.detached");
        new s0("ETSI.RFC3161");
        new s0("Extend");
        new s0("ExtensionLevel");
        new s0("ExportState");
        new s0("Far");
        new s0("FB");
        new s0("FD");
        new s0("FDecodeParms");
        new s0("FDF");
        new s0("Ff");
        new s0("FFilter");
        new s0("FG");
        new s0("FieldMDP");
        new s0("FileAttachment");
        new s0("Fit");
        new s0("FitR");
        new s0("FitB");
        new s0(ExifInterface.TAG_FLASH);
        new s0("FlashVars");
        new s0("FontFamily");
        new s0("FontMatrix");
        new s0("FontWeight");
        new s0("Foreground");
        new s0("FreeText");
        new s0("FRM");
        new s0("FS");
        new s0("FT");
        new s0("Function");
        new s0("Functions");
        new s0("FunctionType");
        new s0("GBK");
        new s0("GCS");
        new s0("GEO");
        new s0("GEOGCS");
        new s0("Glitter");
        new s0("GoTo3DView");
        new s0("GoToE");
        new s0("GPTS");
        new s0("GTS_PDFA1");
        new s0("HalftoneName");
        new s0("HalftoneType");
        new s0("HAlign");
        new s0("Helv");
        new s0("HF");
        new s0("Hid");
        new s0("Hide");
        new s0("Highlight");
        new s0("HOffset");
        new s0("HT");
        new s0("HTP");
        new s0("IC");
        new s0("IF");
        new s0("ImageB");
        new s0("ImageC");
        new s0("ImageI");
        new s0("Ind");
        new s0("Ink");
        new s0("InkList");
        new s0("Instances");
        new s0("ImportData");
        new s0("IRT");
        new s0("ITXT");
        new s0("IX");
        new s0("Lab");
        new s0("Language");
        new s0("Length1");
        new s0("Line");
        new s0("Linear");
        new s0("Location");
        new s0("Lock");
        new s0("LPTS");
        new s0("M");
        new s0("Mac");
        new s0("Material");
        new s0("MacExpertEncoding");
        new s0("max");
        new s0("Max");
        new s0("MaxLen");
        new s0("Measure");
        new s0("min");
        new s0("Min");
        new s0("MK");
        new s0("MMType1");
        new s0("Movie");
        new s0("n0");
        new s0("n1");
        new s0("n2");
        new s0("n3");
        new s0("n4");
        new s0("Navigation");
        new s0("NavigationPane");
        new s0("NChannel");
        new s0("Near");
        new s0("NeedAppearances");
        new s0("NeedsRendering");
        new s0("NM");
        new s0("Not");
        new s0("NumberFormat");
        new s0("OCG");
        new s0("OCMD");
        new s0("OCSP");
        new s0("OCSPs");
        new s0("OE");
        new s0("Off");
        new s0("on");
        new s0("Open");
        new s0("OP");
        new s0("op");
        new s0("OPI");
        new s0("OPM");
        new s0("Opt");
        new s0("Or");
        new s0("Org");
        new s0("Oscillating");
        new s0("PageElement");
        new s0("ParentTreeNextKey");
        new s0("PassContextClick");
        new s0("pb");
        new s0("PC");
        new s0("PDF");
        new s0("PDFDocEncoding");
        new s0("PDU");
        new s0("Perms");
        new s0("PI");
        new s0("PieceInfo");
        new s0("PlayCount");
        new s0("PO");
        new s0("Polygon");
        new s0("PolyLine");
        new s0("Popup");
        new s0("Position");
        new s0("Preferred");
        new s0("Presentation");
        new s0("PreserveRB");
        new s0("PresSteps");
        new s0("PrinterMark");
        new s0("PrintField");
        new s0("PrintState");
        new s0("ProcSet");
        new s0("PROJCS");
        new s0("Prop_Build");
        new s0("PS");
        new s0("PtData");
        new s0("Adobe.PubSec");
        new s0("PV");
        new s0("Q");
        new s0("QuadPoints");
        new s0("Range");
        new s0("rb");
        new s0("RC");
        new s0("RD");
        new s0("Reason");
        new s0("Recipients");
        new s0("ResetForm");
        new s0("Requirements");
        new s0("RI");
        new s0("RichMedia");
        new s0("RichMediaActivation");
        new s0("RichMediaAnimation");
        new s0("RichMediaCommand");
        new s0("RichMediaConfiguration");
        new s0("RichMediaContent");
        new s0("RichMediaDeactivation");
        new s0("RichMediaExecute");
        new s0("RichMediaInstance");
        new s0("RichMediaParams");
        new s0("RichMediaPosition");
        new s0("RichMediaPresentation");
        new s0("RichMediaSettings");
        new s0("RichMediaWindow");
        new s0("RL");
        new s0("Role");
        new s0("RV");
        new s0("Schema");
        new s0("Scripts");
        new s0("Separation");
        new s0("SetOCGState");
        new s0("Settings");
        new s0("ShadingType");
        new s0("Shift-JIS");
        new s0("Sig");
        new s0("SigFieldLock");
        new s0("SigRef");
        new s0("SMaskInData");
        new s0("Sort");
        new s0("Sound");
        new s0("Speed");
        new s0("Split");
        new s0("Square");
        new s0("Squiggly");
        new s0("SS");
        new s0("St");
        new s0("Stamp");
        new s0("Status");
        new s0("Standard");
        new s0("State");
        new s0("StmF");
        new s0("StrF");
        new s0("StrikeOut");
        new s0("SubFilter");
        new s0("SubmitForm");
        new s0("SV");
        new s0("SW");
        new s0("TA");
        new s0("TR2");
        new s0("Thumb");
        new s0(MemoryUtils.THREADS);
        new s0("TI");
        new s0("Time");
        new s0("TK");
        new s0("TM");
        new s0("Toggle");
        new s0(Toolbar.TAG);
        new s0("TP");
        new s0("TR");
        new s0("Trans");
        new s0("TransformParams");
        new s0("TransformMethod");
        new s0("Transparent");
        new s0("TrapNet");
        new s0("TS");
        new s0("Ttl");
        new s0("TU");
        new s0("tv");
        new s0("Tx");
        new s0("Type3");
        new s0("UE");
        new s0("UHC");
        new s0("Unix");
        new s0("UR");
        new s0("UR3");
        new s0("URL");
        new s0("User");
        new s0("UserUnit");
        new s0("utf_8");
        new s0("V2");
        new s0("VAlign");
        new s0("VE");
        new s0("VeriSign.PPKVS");
        new s0("Vertices");
        new s0("Video");
        new s0("Views");
        new s0("Viewport");
        new s0("ViewState");
        new s0("VOffset");
        new s0("VP");
        new s0("VRI");
        new s0("Watermark");
        new s0("Widget");
        new s0("Window");
        new s0("Windowed");
        new s0("Wipe");
        new s0("WKT");
        new s0("XA");
        new s0("XD");
        new s0("XFA");
        new s0("XPTS");
        new s0("XRefStm");
        new s0("ZaDb");
        Field[] declaredFields = s0.class.getDeclaredFields();
        C6 = new HashMap(declaredFields.length);
        int i7 = 0;
        while (i7 < declaredFields.length) {
            try {
                Field field = declaredFields[i7];
                if ((field.getModifiers() & 25) == 25 && field.getType().equals(s0.class)) {
                    s0 s0Var = (s0) field.get((Object) null);
                    C6.put(qqq(s0Var.toString()), s0Var);
                }
                i7++;
            } catch (Exception e7) {
                e7.printStackTrace();
                return;
            }
        }
    }

    public s0(String str) {
        this(str, true);
    }

    public static byte[] eee(String str) {
        int length = str.length();
        rg rgVar = new rg(length + 20);
        rgVar.de('/');
        char[] charArray = str.toCharArray();
        for (int i7 = 0; i7 < length; i7++) {
            char c = (char) (charArray[i7] & 255);
            if (c == ' ' || c == '#' || c == '%' || c == '/' || c == '<' || c == '>' || c == '[' || c == ']' || c == '{' || c == '}' || c == '(' || c == ')') {
                rgVar.de('#');
                rgVar.uk(Integer.toString(c, 16));
            } else if (c < ' ' || c > '~') {
                rgVar.de('#');
                if (c < 16) {
                    rgVar.de('0');
                }
                rgVar.uk(Integer.toString(c, 16));
            } else {
                rgVar.de(c);
            }
        }
        return rgVar.mmm();
    }

    public static String qqq(String str) {
        StringBuffer stringBuffer = new StringBuffer();
        try {
            int length = str.length();
            int i7 = 1;
            while (i7 < length) {
                char charAt = str.charAt(i7);
                if (charAt == '#') {
                    char charAt2 = str.charAt(i7 + 1);
                    i7 += 2;
                    charAt = (char) ((PRTokeniser.th(charAt2) << 4) + PRTokeniser.th(str.charAt(i7)));
                }
                stringBuffer.append(charAt);
                i7++;
            }
        } catch (IndexOutOfBoundsException unused) {
        }
        return stringBuffer.toString();
    }

    /* renamed from: aaa */
    public int compareTo(s0 s0Var) {
        byte[] bArr = this.f9852ad;
        byte[] bArr2 = s0Var.f9852ad;
        int min = Math.min(bArr.length, bArr2.length);
        for (int i7 = 0; i7 < min; i7++) {
            if (bArr[i7] > bArr2[i7]) {
                return 1;
            }
            if (bArr[i7] < bArr2[i7]) {
                return -1;
            }
        }
        if (bArr.length < bArr2.length) {
            return -1;
        }
        return bArr.length > bArr2.length ? 1 : 0;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof s0) || compareTo((s0) obj) != 0) {
            return false;
        }
        return true;
    }

    public int hashCode() {
        int i7 = this.f9760uk;
        if (i7 == 0) {
            int length = this.f9852ad.length;
            int i8 = 0;
            int i9 = 0;
            while (i8 < length) {
                i7 = (i7 * 31) + (this.f9852ad[i9] & 255);
                i8++;
                i9++;
            }
            this.f9760uk = i7;
        }
        return i7;
    }

    public s0(String str, boolean z7) {
        super(4);
        this.f9760uk = 0;
        int length = str.length();
        if (!z7 || length <= 127) {
            this.f9852ad = eee(str);
        } else {
            throw new IllegalArgumentException(qw.ad("the.name.1.is.too.long.2.characters", str, String.valueOf(length)));
        }
    }

    public s0(byte[] bArr) {
        super(4, bArr);
        this.f9760uk = 0;
    }
}
