package com.baidu.swan.game.ad.utils;

import android.text.TextUtils;
import com.baidu.swan.game.ad.ioc.SwanAdRuntime;
import java.util.HashMap;
import java.util.Map;

public class AdErrorCode {
    public static final String ADPLACE_ID_MISS = "107000";
    public static final String ADPLACE_ID_NOT_ENABLE = "107002";
    public static final String ADPLACE_ID_NOT_EXIST = "107001";
    public static final String AD_ACT_MISS = "201030";
    public static final String AD_ACT_NOT_IDENTIFY = "201031";
    public static final String AD_CREATIVE_MISS = "201020";
    public static final String AD_CREATIVE_NOT_IDENTIFY = "201021";
    public static final String AD_NO_SIGN = "201010";
    public static final String AD_PARAMETER_ERROR = "3010007";
    public static final String AD_REQUEST_FAIL = "3010002";
    public static final String AD_WIDGET_ADD_FAILURE = "3010000";
    public static final String AD_WIDGET_ADD_SUCCESS = "4010000";
    public static final String ANDROID_ID_ERR = "104081";
    public static final String ANDROID_ID_MISS = "104080";
    public static final String APPID_ERROR = "101005";
    public static final String APPINFO_MISSING = "103000";
    public static final String APP_ID_ERROR = "103011";
    public static final String APP_ID_INFO_MISSING = "103010";
    public static final String APP_ID_INVALID = "103012";
    public static final String APP_MAIN_VERSION_INFO_MISSING = "103040";
    public static final String APP_OS_MISSING = "103050";
    public static final String APP_PK_ERROR = "103060";
    public static final String APP_SIZE_MISS = "201090";
    public static final String APP_VERSION_INFO_MISSING = "103030";
    public static final String BANNER_AD_FIRST_REJECT = "3010012";
    public static final String BANNER_AD_NO_AVAILABLE = "3010010";
    public static final String BANNER_AD_REJECT = "3010011";
    public static final String BANNER_AD_REPEAT_REJECT = "3010013";
    public static final String CHANNEL_ID_ERROR = "103020";
    public static final String CONNECT_TYPE_ERR = "105021";
    public static final String CONNECT_TYPE_MISS = "105020";
    public static final String COORDINATE_ERR = "106001";
    public static final String COORDINATE_MISS = "106000";
    public static final String CURL_MISS = "201050";
    public static final String DES_MISS = "201070";
    public static final String DEVICE_INFO_MISSING = "104000";
    public static final String DEVICE_TYPE_ERROR = "104011";
    public static final String DEVICE_TYPE_MISSING = "104010";
    public static final String DEV_TY_MISS = "104060";
    public static final String DEV_UNIQUE_ERR = "104071";
    public static final String DEV_UNIQUE_MISS = "104070";
    public static final String HEIGHT_MISS = "104110";
    public static final String ICON_MISS = "201100";
    public static final String LATITUDE_MISS = "106020";
    public static final String LOCATION_TIME_MISS = "106030";
    public static final String LONGITUDE_MISS = "106010";
    public static final String MAKER_MISSING = "104050";
    public static final String MET_ADRESS_ERR = "105011";
    public static final String NETWORK_CONNECT_ERROR = "3010003";
    public static final String NET_ADDRESS_MISS = "105010";
    public static final String NET_INFO_MISS = "105000";
    public static final String NET_NOT_SATISFY = "107050";
    public static final String NOT_ALLOW_REQUEST_AD = "3010006";
    public static final String NOT_REPEAT_REQUEST_AD = "3010005";
    public static final String NO_AD = "200000";
    public static final String NO_AD_CAN_SHOW = "3010004";
    public static final String NO_AD_DATA = "201000";
    public static final String OPERATOR_ERR = "105031";
    public static final String OPERATOR_MISS = "105030";
    public static final String OS_INFO_ERROR = "104021";
    public static final String OS_MAIN_VERSION_MISS = "104040";
    public static final String OS_MISSING = "104020";
    public static final String OS_VERSION_MISS = "104030";
    public static final String PIC_MISS = "201110";
    public static final String PK_MISS = "201080";
    public static final String PLACEID_APPID_NOT_MATCH = "107003";
    public static final String PLACEID_HEIGHT_MISS = "107030";
    public static final String PLACEID_MISS = "107040";
    public static final String PLACEID_SIZE_MISS = "107010";
    public static final String PLACEID_WIDTH_MISS = "107020";
    public static final String PLAYER_INTERNAL_ERROR = "3010001";
    public static final String REFERER_ERROR = "101004";
    public static final String REQUEST_FORMAT_ERROR = "100000";
    public static final String REQUEST_ID_FORMAT_ERROR = "101001";
    public static final String REQUEST_ID_MISSING = "101000";
    public static final String REQUEST_TRFTP_MISSING = "101002";
    public static final String REWARD_AD_REPEAT_INIT_ERR = "3010009";
    public static final String REWARD_VIDEO_URL_NULL = "3010008";
    public static final String SCREEN_SIZE_MISS = "104090";
    public static final String SDK_VERSION_ERROR = "101003";
    public static final String SIZE_NOT_MATCH = "107052";
    public static final String TIT_MISS = "201060";
    public static final String VIDEO_TIT_TOO_LONG = "107051";
    public static final String WIDTH_MISS = "104100";
    public static final String WIFI_HOT_ERR = "105041";
    public static final String WIFI_HOT_MISS = "105050";
    public static final String WIFI_HOT_NAME_MISS = "105060";
    public static final String WIFI_INFO_MISS = "105040";
    public static final String WIFI_STATE_MISS = "105070";
    public static final String WINURL_MISS = "201040";
    private static Map<String, String> sErrorMap;

    static {
        HashMap hashMap = new HashMap();
        sErrorMap = hashMap;
        hashMap.put("100000", "请求格式错误");
        sErrorMap.put(REQUEST_ID_MISSING, "请求ID信息缺失");
        sErrorMap.put(REQUEST_ID_FORMAT_ERROR, "请求ID不符合约定格式");
        sErrorMap.put(REQUEST_TRFTP_MISSING, "请求的trftp信息缺失");
        sErrorMap.put(SDK_VERSION_ERROR, "请求的sdk版本信息有误");
        sErrorMap.put(REFERER_ERROR, "请求的referer信息有误");
        sErrorMap.put(APPID_ERROR, "请求的appid不合法");
        sErrorMap.put(APPINFO_MISSING, "应用信息缺失");
        sErrorMap.put(APP_ID_INFO_MISSING, "应用ID信息缺失");
        sErrorMap.put(APP_ID_ERROR, "应用ID信息错误，MSSP未收录");
        sErrorMap.put(APP_ID_INVALID, "应用ID无效，MSSP上未生效");
        sErrorMap.put(CHANNEL_ID_ERROR, "应用ID无效，渠道ID信息错误");
        sErrorMap.put(APP_VERSION_INFO_MISSING, "应用版本信息缺失");
        sErrorMap.put(APP_MAIN_VERSION_INFO_MISSING, "应用主版本信息缺失");
        sErrorMap.put(APP_OS_MISSING, "应用操作系统信息缺失");
        sErrorMap.put(APP_PK_ERROR, "应用包名信息错误，请保证注册包名和实际请求包名一致");
        sErrorMap.put(DEVICE_INFO_MISSING, "设备信息缺失");
        sErrorMap.put(DEVICE_TYPE_MISSING, "设备类型信息缺失");
        sErrorMap.put(DEVICE_TYPE_ERROR, "设备类型信息错误");
        sErrorMap.put(OS_MISSING, "操作系统信息缺失");
        sErrorMap.put(OS_INFO_ERROR, "操作系统信息错误");
        sErrorMap.put(OS_VERSION_MISS, "操作系统版本信息缺失");
        sErrorMap.put(OS_MAIN_VERSION_MISS, "操作系统主版本信息缺失");
        sErrorMap.put(MAKER_MISSING, "厂商信息缺失");
        sErrorMap.put(DEV_TY_MISS, "设备型号信息缺失");
        sErrorMap.put(DEV_UNIQUE_MISS, "设备唯一标识符缺失");
        sErrorMap.put(DEV_UNIQUE_ERR, "设备唯一标识符错误");
        sErrorMap.put(ANDROID_ID_MISS, "android id 缺失");
        sErrorMap.put(ANDROID_ID_ERR, "android id 格式错误");
        sErrorMap.put(SCREEN_SIZE_MISS, "设备屏幕尺寸信息缺失");
        sErrorMap.put(WIDTH_MISS, "设备屏幕尺寸宽度缺失");
        sErrorMap.put(HEIGHT_MISS, "设备屏幕尺寸高度缺失");
        sErrorMap.put(NET_INFO_MISS, "网络环境信息缺失");
        sErrorMap.put(NET_ADDRESS_MISS, "网络地址信息缺失");
        sErrorMap.put(MET_ADRESS_ERR, "网络地址信息格式错误");
        sErrorMap.put(CONNECT_TYPE_MISS, "网络连接类型缺失");
        sErrorMap.put(CONNECT_TYPE_ERR, "网络连接类型错误");
        sErrorMap.put(OPERATOR_MISS, "网络运营商类型缺失");
        sErrorMap.put(OPERATOR_ERR, "网络运营商类型错误");
        sErrorMap.put(WIFI_INFO_MISS, "Wi-Fi热点地址信息缺失");
        sErrorMap.put(WIFI_HOT_ERR, "Wi-Fi热点地址信息格式错误");
        sErrorMap.put(WIFI_HOT_MISS, "Wi-Fi热点信号强度信息缺失");
        sErrorMap.put(WIFI_HOT_NAME_MISS, "Wi-Fi热点名称缺失");
        sErrorMap.put(WIFI_STATE_MISS, "Wi-Fi连接状态信息缺失");
        sErrorMap.put(COORDINATE_MISS, "坐标类型信息缺失");
        sErrorMap.put(COORDINATE_ERR, "坐标类型信息错误");
        sErrorMap.put(LONGITUDE_MISS, "经度信息缺失");
        sErrorMap.put(LATITUDE_MISS, "纬度信息缺失");
        sErrorMap.put(LOCATION_TIME_MISS, "定位时间戳信息缺失");
        sErrorMap.put(ADPLACE_ID_MISS, "广告位ID缺失");
        sErrorMap.put(ADPLACE_ID_NOT_EXIST, "广告位ID未收录");
        sErrorMap.put(ADPLACE_ID_NOT_ENABLE, "广告位ID未启用");
        sErrorMap.put(PLACEID_APPID_NOT_MATCH, "广告位ID与应用ID不匹配");
        sErrorMap.put(PLACEID_SIZE_MISS, "广告位尺寸信息缺失");
        sErrorMap.put(PLACEID_WIDTH_MISS, "广告位尺寸宽度缺失");
        sErrorMap.put(PLACEID_HEIGHT_MISS, "广告位尺寸高度缺失");
        sErrorMap.put(PLACEID_MISS, "广告位信息缺失");
        sErrorMap.put(NET_NOT_SATISFY, "视频广告的网络条件无法满足");
        sErrorMap.put(VIDEO_TIT_TOO_LONG, "视频标题名称过长");
        sErrorMap.put(SIZE_NOT_MATCH, "SDK传递的广告位比例与MSSP的广告位比例不一致");
        sErrorMap.put(NO_AD, "无广告返回");
        sErrorMap.put(NO_AD_DATA, "无广告数据");
        sErrorMap.put(AD_NO_SIGN, "广告无签名");
        sErrorMap.put(AD_CREATIVE_MISS, "广告创意类型信息缺失");
        sErrorMap.put(AD_CREATIVE_NOT_IDENTIFY, "广告创意类型信息无法识别");
        sErrorMap.put(AD_ACT_MISS, "广告动作类型信息缺失");
        sErrorMap.put(AD_ACT_NOT_IDENTIFY, "广告动作类型信息无法识别");
        sErrorMap.put(WINURL_MISS, "曝光汇报地址丢失");
        sErrorMap.put(CURL_MISS, "点击响应地址丢失");
        sErrorMap.put(TIT_MISS, "推广标题丢失");
        sErrorMap.put(DES_MISS, "推广描述丢失");
        sErrorMap.put(PK_MISS, "推广应用包名丢失");
        sErrorMap.put(APP_SIZE_MISS, "推广应用包大小丢失");
        sErrorMap.put(ICON_MISS, "推广图标丢失");
        sErrorMap.put(PIC_MISS, "推广图片丢失");
        sErrorMap.put(AD_WIDGET_ADD_FAILURE, "广告组件挂载失败");
        sErrorMap.put(PLAYER_INTERNAL_ERROR, "播放器内部错误");
        sErrorMap.put(AD_REQUEST_FAIL, "广告请求失败");
        sErrorMap.put(NETWORK_CONNECT_ERROR, "网络连接错误");
        sErrorMap.put(NO_AD_CAN_SHOW, "没有可以展示的广告");
        sErrorMap.put(NOT_REPEAT_REQUEST_AD, "广告正在拉取中，不能重复请求");
        sErrorMap.put(NOT_ALLOW_REQUEST_AD, "广告正在展示中，不能请求广告");
        sErrorMap.put(AD_PARAMETER_ERROR, "gameId、appsid、adUnitid其中一个为空，不能请求广告");
        sErrorMap.put(AD_WIDGET_ADD_SUCCESS, "广告组件准备完成");
        sErrorMap.put(REWARD_VIDEO_URL_NULL, "播放地址为空");
        sErrorMap.put(REWARD_AD_REPEAT_INIT_ERR, "激励视频重复调用create错误");
        sErrorMap.put(BANNER_AD_NO_AVAILABLE, "没有可以show的banner广告");
        sErrorMap.put(BANNER_AD_REJECT, "广告关闭生效中，本次请求被拒绝");
        sErrorMap.put(BANNER_AD_FIRST_REJECT, "小游戏启动前%d秒不允许展示banner广告");
        sErrorMap.put(BANNER_AD_REPEAT_REJECT, "banner广告展示频控限制，%d秒内不允许重复展示banner广告");
    }

    public static String errorMsg(String errorCode) {
        String errorMsg = sErrorMap.get(errorCode);
        if (errorMsg == null) {
            errorMsg = "";
        }
        return formatMessage(errorCode, errorMsg);
    }

    public static String formatMessage(String errorCode, String errorMsg) {
        if (TextUtils.equals(BANNER_AD_FIRST_REJECT, errorCode)) {
            return String.format(errorMsg, new Object[]{Long.valueOf(SwanAdRuntime.getAdConfig().getBannerAdStartShowTime() / 1000)});
        } else if (!TextUtils.equals(BANNER_AD_REPEAT_REJECT, errorCode)) {
            return errorMsg;
        } else {
            return String.format(errorMsg, new Object[]{Long.valueOf(SwanAdRuntime.getAdConfig().getBannerAdRepeatShowTime() / 1000)});
        }
    }
}
