package com.baidu.searchbox.video.collectionflow.clearscreen.detail;

import com.baidu.searchbox.feed.detail.arch.SlotComponentUnit;
import com.baidu.searchbox.feed.detail.arch.SlotUnit;
import com.baidu.searchbox.feed.detail.arch.ext.CommonState;
import com.baidu.searchbox.feed.detail.arch.ext.CoreReducer;
import com.baidu.searchbox.feed.detail.arch.ext.InterceptorToParentReducer;
import com.baidu.searchbox.feed.detail.frame.Middleware;
import com.baidu.searchbox.feed.detail.frame.Reducer;
import com.baidu.searchbox.video.collectionflow.detail.CollectionVideoItemLayoutReducer;
import com.baidu.searchbox.video.collectionflow.detail.bottombanner.CollectionBottomBannerReducer;
import com.baidu.searchbox.video.collectionflow.detail.parise.CollectionPraiseReducer;
import com.baidu.searchbox.video.collectionflow.detail.player.CollectionPlayerLoopReducer;
import com.baidu.searchbox.video.collectionflow.unit.CollectionAirPlayClarityUnit;
import com.baidu.searchbox.video.collectionflow.unit.CollectionBarrageInputBarUnit;
import com.baidu.searchbox.video.collectionflow.unit.CollectionExclusiveLabelUnit;
import com.baidu.searchbox.video.collectionflow.unit.CollectionProtocolUnit;
import com.baidu.searchbox.video.collectionflow.unit.PreviewUnit;
import com.baidu.searchbox.video.collectionflow.unit.RewardUnit;
import com.baidu.searchbox.video.component.history.CommonHistoryReducer;
import com.baidu.searchbox.video.feedflow.ad.als.AlsReducer;
import com.baidu.searchbox.video.feedflow.common.IntentDataReducer;
import com.baidu.searchbox.video.feedflow.common.LogMiddleware;
import com.baidu.searchbox.video.feedflow.common.ParamExtMiddleware;
import com.baidu.searchbox.video.feedflow.detail.FlowDetailMiddleware;
import com.baidu.searchbox.video.feedflow.detail.FlowDetailReducer;
import com.baidu.searchbox.video.feedflow.detail.air.AirTimerCountReducer;
import com.baidu.searchbox.video.feedflow.detail.author.AuthorReducer;
import com.baidu.searchbox.video.feedflow.detail.banner.BannerReducer;
import com.baidu.searchbox.video.feedflow.detail.banner.goods.GoodsBigBannerReducer;
import com.baidu.searchbox.video.feedflow.detail.barrage.BarrageReducer;
import com.baidu.searchbox.video.feedflow.detail.barrage.iconentrance.BarrageIconEntranceUnit;
import com.baidu.searchbox.video.feedflow.detail.chat.ChatroomEntranceMiddleware;
import com.baidu.searchbox.video.feedflow.detail.chat.ChatroomEntranceReducer;
import com.baidu.searchbox.video.feedflow.detail.claritypanel.ClarityPanelMiddleware;
import com.baidu.searchbox.video.feedflow.detail.claritypanel.ClarityPanelReducer;
import com.baidu.searchbox.video.feedflow.detail.claritypanel.statistic.ClarityPanelStatisticMiddleware;
import com.baidu.searchbox.video.feedflow.detail.collectionfavor.CollectionCollectMiddleware;
import com.baidu.searchbox.video.feedflow.detail.combopraise.ComboPraiseMiddleware;
import com.baidu.searchbox.video.feedflow.detail.combopraise.ComboPraiseReducer;
import com.baidu.searchbox.video.feedflow.detail.combopraise.statistic.ComboPraiseStatisticReducer;
import com.baidu.searchbox.video.feedflow.detail.comment.CommentReducer;
import com.baidu.searchbox.video.feedflow.detail.comment.emojipanel.EmojiPanelMiddleware;
import com.baidu.searchbox.video.feedflow.detail.comment.emojipanel.EmojiPanelReducer;
import com.baidu.searchbox.video.feedflow.detail.comment.statistic.CommentStatisticReducer;
import com.baidu.searchbox.video.feedflow.detail.commentbubble.CommentBubbleUnit;
import com.baidu.searchbox.video.feedflow.detail.controlvisible.GroupControlUnit;
import com.baidu.searchbox.video.feedflow.detail.copyurl.CopyUrlReducer;
import com.baidu.searchbox.video.feedflow.detail.defaultcombopraise.DefaultComboPraiseMiddleware;
import com.baidu.searchbox.video.feedflow.detail.defaultcombopraise.DefaultComboPraiseReducer;
import com.baidu.searchbox.video.feedflow.detail.dislike.DislikeNewPanelUnit;
import com.baidu.searchbox.video.feedflow.detail.error.NetErrorReducer;
import com.baidu.searchbox.video.feedflow.detail.favor.FavorMiddleware;
import com.baidu.searchbox.video.feedflow.detail.favor.FavorReducer;
import com.baidu.searchbox.video.feedflow.detail.foldscreen.FoldScreenInnerMiddleware;
import com.baidu.searchbox.video.feedflow.detail.fullplay.FullPlayReducer;
import com.baidu.searchbox.video.feedflow.detail.fullplay.statistic.FullPlayStatisticMiddleware;
import com.baidu.searchbox.video.feedflow.detail.history.HistoryMiddleware;
import com.baidu.searchbox.video.feedflow.detail.hotcomment.HotCommentReducer;
import com.baidu.searchbox.video.feedflow.detail.intercept.InterceptStateUnit;
import com.baidu.searchbox.video.feedflow.detail.landscapefold.LandscapeFoldReducer;
import com.baidu.searchbox.video.feedflow.detail.landscapelistpanel.LandscapeListPanelShowReducer;
import com.baidu.searchbox.video.feedflow.detail.landscapelistpanel.statistic.LandscapeListPanelStatisticReducer;
import com.baidu.searchbox.video.feedflow.detail.landscapenextguide.LandscapeNextGuideUnit;
import com.baidu.searchbox.video.feedflow.detail.listpanel.ListPanelReducer;
import com.baidu.searchbox.video.feedflow.detail.listpanel.statistic.ListPanelStatisticMiddleware;
import com.baidu.searchbox.video.feedflow.detail.longpressspeed.LongPressSpeedReducer;
import com.baidu.searchbox.video.feedflow.detail.longpressspeed.LongPressSpeedStatisticMiddleware;
import com.baidu.searchbox.video.feedflow.detail.longpressspeed.duration.LongPressForwardDurationUnit;
import com.baidu.searchbox.video.feedflow.detail.mask.MaskReducer;
import com.baidu.searchbox.video.feedflow.detail.night.NightModeReducer;
import com.baidu.searchbox.video.feedflow.detail.offline.OfflineMiddleware;
import com.baidu.searchbox.video.feedflow.detail.offline.OfflineReducer;
import com.baidu.searchbox.video.feedflow.detail.onekeytriple.OneKeyTripleReducer;
import com.baidu.searchbox.video.feedflow.detail.oneton.OneToNReducer;
import com.baidu.searchbox.video.feedflow.detail.player.reducer.PlayerReducer;
import com.baidu.searchbox.video.feedflow.detail.praise.PraiseMiddleware;
import com.baidu.searchbox.video.feedflow.detail.report.ReportReducer;
import com.baidu.searchbox.video.feedflow.detail.riskwarning.DangerHintReducer;
import com.baidu.searchbox.video.feedflow.detail.rumor.RumorUnit;
import com.baidu.searchbox.video.feedflow.detail.sandwich.SandwichPortraitTimeUnit;
import com.baidu.searchbox.video.feedflow.detail.search.SearchMiddleware;
import com.baidu.searchbox.video.feedflow.detail.seekbar.SeekBarMiddleware;
import com.baidu.searchbox.video.feedflow.detail.seekbar.SeekBarReducer;
import com.baidu.searchbox.video.feedflow.detail.shortplay.ShortPlayWatchingUnit;
import com.baidu.searchbox.video.feedflow.detail.speed.SpeedPanelReducer;
import com.baidu.searchbox.video.feedflow.detail.speed.SpeedPanelStatisticMiddleware;
import com.baidu.searchbox.video.feedflow.detail.speedout.SpeedOutUnit;
import com.baidu.searchbox.video.feedflow.detail.statusbar.StatusBarMaskReducer;
import com.baidu.searchbox.video.feedflow.detail.subscribe.SubscribeMiddleware;
import com.baidu.searchbox.video.feedflow.detail.subscribe.SubscribeReducer;
import com.baidu.searchbox.video.feedflow.detail.successarrive.SuccessRenderMiddleware;
import com.baidu.searchbox.video.feedflow.detail.successarrive.SuccessRenderReducer;
import com.baidu.searchbox.video.feedflow.detail.summary.SummaryReducer;
import com.baidu.searchbox.video.feedflow.detail.talosgoodspanel.TalosPanelReducer;
import com.baidu.searchbox.video.feedflow.detail.talospanellandscape.LandscapeTalosPanelReducer;
import com.baidu.searchbox.video.feedflow.detail.thirdParty.ThirdPartyReducer;
import com.baidu.searchbox.video.feedflow.detail.thirdParty.statistic.ThirdPartyStatisticMiddleware;
import com.baidu.searchbox.video.feedflow.detail.toptitle.TopTitleReducer;
import com.baidu.searchbox.video.feedflow.detail.toptitle.image.TopImageTitleUnit;
import com.baidu.searchbox.video.feedflow.detail.ubc.FlowDetailUbcReducer;
import com.baidu.searchbox.video.feedflow.detail.vote.VoteInfoUnit;
import com.baidu.searchbox.video.feedflow.di.DIFactory;
import com.baidu.searchbox.video.feedflow.flow.collection.autonextguide.AutoNextGuideReducer;
import com.baidu.searchbox.video.feedflow.flow.collection.autonextguide.CollectionBackGuideReducer;
import com.baidu.searchbox.video.feedflow.flow.collection.collectionrecord.CollectionRecordMiddleware;
import com.baidu.searchbox.video.feedflow.flow.collectionfold.FoldCollectionPanelDataTransformMiddleware;
import com.baidu.searchbox.video.feedflow.flow.enterpathway.EnterPathWayUnit;
import com.baidu.searchbox.video.feedflow.flow.exc.ExcMiddleware;
import com.baidu.searchbox.video.feedflow.flow.fontsize.FontSizeReducer;
import com.baidu.searchbox.video.feedflow.flow.guidemanager.FlowVideoGuideReducer;
import com.baidu.searchbox.video.feedflow.flow.more.MoreDetailActionInterceptorMiddleware;
import com.baidu.searchbox.video.feedflow.flow.more.MoreFlowReducerAdapterMiddleware;
import com.baidu.searchbox.video.feedflow.flow.offline.OfflineMiddlewareAdapter;
import com.baidu.searchbox.video.feedflow.flow.search.SearchMarkFlowMiddleware;
import com.baidu.searchbox.video.feedflow.flow.speed.SpeedSyncMiddleware;
import com.baidu.searchbox.video.feedflow.provider.ClearScreenCollectionVideoItemUnitProvider;
import com.baidu.searchbox.video.middleware.NetCheckMiddleware;
import java.util.ArrayList;
import java.util.List;
import kotlin.Metadata;

@Metadata(d1 = {"\u0000\u001c\n\u0000\n\u0002\u0010!\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\u001a\u001c\u0010\u0000\u001a\u000e\u0012\n\u0012\b\u0012\u0004\u0012\u00020\u00030\u00020\u00012\u0006\u0010\u0004\u001a\u00020\u0005H\u0002\u001a\u001c\u0010\u0006\u001a\u000e\u0012\n\u0012\b\u0012\u0004\u0012\u00020\u00030\u00070\u00012\u0006\u0010\u0004\u001a\u00020\u0005H\u0002¨\u0006\b"}, d2 = {"collectReducer", "", "Lcom/baidu/searchbox/feed/detail/frame/Reducer;", "Lcom/baidu/searchbox/feed/detail/arch/ext/CommonState;", "provider", "Lcom/baidu/searchbox/video/feedflow/provider/ClearScreenCollectionVideoItemUnitProvider;", "collectionMiddleware", "Lcom/baidu/searchbox/feed/detail/frame/Middleware;", "collection-flow_release"}, k = 2, mv = {1, 6, 0}, xi = 48)
/* compiled from: ClearScreenCollectionVideoItemStore.kt */
public final class ClearScreenCollectionVideoItemStoreKt {
    /* access modifiers changed from: private */
    public static final List<Middleware<CommonState>> collectionMiddleware(ClearScreenCollectionVideoItemUnitProvider provider) {
        List arrayList = new ArrayList();
        List $this$collectionMiddleware_u24lambda_u2d4 = arrayList;
        $this$collectionMiddleware_u24lambda_u2d4.add(new LogMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new NetCheckMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new ParamExtMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(InterceptStateUnit.INSTANCE.createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.add(new FlowDetailMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new MoreDetailActionInterceptorMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new OfflineMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new OfflineMiddlewareAdapter());
        $this$collectionMiddleware_u24lambda_u2d4.add(new PraiseMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new ComboPraiseMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new ExcMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new DefaultComboPraiseMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new SearchMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new SubscribeMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new FavorMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(provider.getShareUnit().createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.add(new LongPressSpeedStatisticMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new ListPanelStatisticMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new ClarityPanelStatisticMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new HistoryMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new MoreFlowReducerAdapterMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new SearchMarkFlowMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new FullPlayStatisticMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new SpeedPanelStatisticMiddleware());
        SlotUnit $this$collectionMiddleware_u24lambda_u2d4_u24lambda_u2d0 = provider.getVideoFlowCommonUnit();
        if ($this$collectionMiddleware_u24lambda_u2d4_u24lambda_u2d0 != null) {
            $this$collectionMiddleware_u24lambda_u2d4.addAll($this$collectionMiddleware_u24lambda_u2d4_u24lambda_u2d0.createMiddlewares());
        }
        $this$collectionMiddleware_u24lambda_u2d4.addAll(new RewardUnit().createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.add(new ClarityPanelMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(provider.getPlayerUnit().createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.add(new FoldScreenInnerMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new CollectionCollectMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new CollectionRecordMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new SuccessRenderMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(provider.getFavorUnit().createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.add(new FoldCollectionPanelDataTransformMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(provider.getLongPressNewMoreUnit().createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(DislikeNewPanelUnit.INSTANCE.createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(provider.getVideoSettingUnit().createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.add(new ThirdPartyStatisticMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new ChatroomEntranceMiddleware());
        if (DIFactory.INSTANCE.getConfig().getShowPlayerSpeedOutSwitch()) {
            $this$collectionMiddleware_u24lambda_u2d4.addAll(SpeedOutUnit.INSTANCE.createMiddlewares());
        }
        $this$collectionMiddleware_u24lambda_u2d4.add(new SeekBarMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.add(new SpeedSyncMiddleware());
        List $this$collectionMiddleware_u24lambda_u2d4_u24lambda_u2d2 = provider.getVideoItemTcStatisticMiddleware();
        if ($this$collectionMiddleware_u24lambda_u2d4_u24lambda_u2d2 != null) {
            $this$collectionMiddleware_u24lambda_u2d4.addAll($this$collectionMiddleware_u24lambda_u2d4_u24lambda_u2d2);
        }
        $this$collectionMiddleware_u24lambda_u2d4.addAll(provider.getMoveUpUnit().createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.add(new EmojiPanelMiddleware());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(CollectionBarrageInputBarUnit.INSTANCE.createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(EnterPathWayUnit.INSTANCE.createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(TopImageTitleUnit.INSTANCE.createMiddlewares());
        $this$collectionMiddleware_u24lambda_u2d4.addAll(BarrageIconEntranceUnit.INSTANCE.createMiddlewares());
        return arrayList;
    }

    /* access modifiers changed from: private */
    public static final List<Reducer<CommonState>> collectReducer(ClearScreenCollectionVideoItemUnitProvider provider) {
        List arrayList = new ArrayList();
        List $this$collectReducer_u24lambda_u2d7 = arrayList;
        $this$collectReducer_u24lambda_u2d7.add(new IntentDataReducer());
        $this$collectReducer_u24lambda_u2d7.add(new FlowDetailReducer());
        $this$collectReducer_u24lambda_u2d7.add(new CoreReducer());
        $this$collectReducer_u24lambda_u2d7.add(new FlowDetailUbcReducer());
        $this$collectReducer_u24lambda_u2d7.add(new PlayerReducer());
        $this$collectReducer_u24lambda_u2d7.add(new NetErrorReducer());
        $this$collectReducer_u24lambda_u2d7.add(new OfflineReducer());
        $this$collectReducer_u24lambda_u2d7.add(new InterceptorToParentReducer());
        $this$collectReducer_u24lambda_u2d7.add(GroupControlUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(new AuthorReducer());
        $this$collectReducer_u24lambda_u2d7.add(new CollectionPraiseReducer());
        $this$collectReducer_u24lambda_u2d7.add(new CommentReducer());
        $this$collectReducer_u24lambda_u2d7.add(new CommentStatisticReducer());
        $this$collectReducer_u24lambda_u2d7.add(new SummaryReducer());
        $this$collectReducer_u24lambda_u2d7.add(new FavorReducer());
        $this$collectReducer_u24lambda_u2d7.add(provider.getFavorUnit().createReducer());
        $this$collectReducer_u24lambda_u2d7.add(provider.getShareUnit().createReducer());
        $this$collectReducer_u24lambda_u2d7.add(new RewardUnit().createReducer());
        $this$collectReducer_u24lambda_u2d7.add(new ReportReducer());
        $this$collectReducer_u24lambda_u2d7.add(new SeekBarReducer());
        $this$collectReducer_u24lambda_u2d7.add(new CopyUrlReducer());
        $this$collectReducer_u24lambda_u2d7.add(new CommonHistoryReducer());
        $this$collectReducer_u24lambda_u2d7.add(new ComboPraiseReducer());
        $this$collectReducer_u24lambda_u2d7.add(new DefaultComboPraiseReducer());
        $this$collectReducer_u24lambda_u2d7.add(new ComboPraiseStatisticReducer());
        $this$collectReducer_u24lambda_u2d7.add(new FontSizeReducer());
        $this$collectReducer_u24lambda_u2d7.add(provider.getGestureUnit().createReducer());
        $this$collectReducer_u24lambda_u2d7.add(new CollectionVideoItemLayoutReducer());
        $this$collectReducer_u24lambda_u2d7.add(new MaskReducer());
        $this$collectReducer_u24lambda_u2d7.add(new AlsReducer());
        $this$collectReducer_u24lambda_u2d7.add(new LongPressSpeedReducer());
        $this$collectReducer_u24lambda_u2d7.add(new LandscapeListPanelShowReducer());
        $this$collectReducer_u24lambda_u2d7.add(new ListPanelReducer());
        $this$collectReducer_u24lambda_u2d7.add(new TalosPanelReducer());
        $this$collectReducer_u24lambda_u2d7.add(new LandscapeTalosPanelReducer());
        $this$collectReducer_u24lambda_u2d7.add(new BannerReducer());
        $this$collectReducer_u24lambda_u2d7.add(new HotCommentReducer());
        $this$collectReducer_u24lambda_u2d7.add(new LandscapeListPanelStatisticReducer());
        $this$collectReducer_u24lambda_u2d7.add(new NightModeReducer());
        $this$collectReducer_u24lambda_u2d7.add(new ClarityPanelReducer());
        $this$collectReducer_u24lambda_u2d7.add(new CollectionPlayerLoopReducer());
        SlotComponentUnit $this$collectReducer_u24lambda_u2d7_u24lambda_u2d6 = provider.getPlayerUnit();
        if ($this$collectReducer_u24lambda_u2d7_u24lambda_u2d6 != null) {
            $this$collectReducer_u24lambda_u2d7.add($this$collectReducer_u24lambda_u2d7_u24lambda_u2d6.createReducer());
        }
        $this$collectReducer_u24lambda_u2d7.add(new FullPlayReducer());
        $this$collectReducer_u24lambda_u2d7.add(new TopTitleReducer());
        $this$collectReducer_u24lambda_u2d7.add(new SpeedPanelReducer());
        $this$collectReducer_u24lambda_u2d7.add(new OneToNReducer());
        $this$collectReducer_u24lambda_u2d7.add(new GoodsBigBannerReducer());
        $this$collectReducer_u24lambda_u2d7.add(provider.getMoveUpUnit().createReducer());
        $this$collectReducer_u24lambda_u2d7.add(new DangerHintReducer());
        $this$collectReducer_u24lambda_u2d7.add(new LandscapeFoldReducer());
        $this$collectReducer_u24lambda_u2d7.add(new AutoNextGuideReducer());
        $this$collectReducer_u24lambda_u2d7.add(new CollectionBackGuideReducer());
        $this$collectReducer_u24lambda_u2d7.add(new AirTimerCountReducer());
        $this$collectReducer_u24lambda_u2d7.add(CollectionAirPlayClarityUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(new SuccessRenderReducer());
        $this$collectReducer_u24lambda_u2d7.add(CollectionExclusiveLabelUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(new FlowVideoGuideReducer());
        $this$collectReducer_u24lambda_u2d7.add(new SubscribeReducer());
        $this$collectReducer_u24lambda_u2d7.add(InterceptStateUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(PreviewUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(new OneKeyTripleReducer());
        $this$collectReducer_u24lambda_u2d7.add(new EmojiPanelReducer());
        $this$collectReducer_u24lambda_u2d7.add(new CollectionBottomBannerReducer());
        $this$collectReducer_u24lambda_u2d7.add(provider.getLongPressNewMoreUnit().createReducer());
        $this$collectReducer_u24lambda_u2d7.add(provider.getVideoSettingUnit().createReducer());
        $this$collectReducer_u24lambda_u2d7.add(LandscapeNextGuideUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(RumorUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(new ThirdPartyReducer());
        $this$collectReducer_u24lambda_u2d7.add(new ChatroomEntranceReducer());
        if (DIFactory.INSTANCE.getConfig().getShowPlayerSpeedOutSwitch()) {
            $this$collectReducer_u24lambda_u2d7.add(SpeedOutUnit.INSTANCE.createReducer());
        }
        $this$collectReducer_u24lambda_u2d7.add(new StatusBarMaskReducer());
        $this$collectReducer_u24lambda_u2d7.add(CollectionProtocolUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(new BarrageReducer());
        $this$collectReducer_u24lambda_u2d7.add(new SeekBarReducer());
        $this$collectReducer_u24lambda_u2d7.add(CommentBubbleUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(DislikeNewPanelUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(CollectionBarrageInputBarUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(VoteInfoUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(EnterPathWayUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(LongPressForwardDurationUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(SandwichPortraitTimeUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(ShortPlayWatchingUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(TopImageTitleUnit.INSTANCE.createReducer());
        $this$collectReducer_u24lambda_u2d7.add(BarrageIconEntranceUnit.INSTANCE.createReducer());
        return arrayList;
    }
}
